import type { Metadata } from 'next';
import Link from 'next/link';
import AboutNav from '@/components/AboutNav';

export const metadata: Metadata = {
  title: 'O mnie layout..',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <AboutNav />
      {children}
    </div>
  );
}
